apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  ConnectionStrings__Default: {{ .Values.secrets.connectionString | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.dockerconfigjson }}
