apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: cinemaabyss
type: kubernetes.io/dockerconfigjson
data:
  # Replace with: cat ~/.docker/config.json | base64 -w0
  .dockerconfigjson: REPLACE_WITH_BASE64_OF_DOCKER_CONFIG_JSON
